server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.today:1521:XE
    username: C##HIGHCARE
    password: HIGHCARE
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  web:
    resources:
      static-locations: classpath:/images/
  # cookie
  server:
    servlet:
      session:
        cookie:
          same-site: none
          secure: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hdhye89@gmail.com
    password: aedelgcwhhiexqpt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # redis cache config
  redis:
    host: localhost
    port: 6379
  # jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate:
        '[format_sql]': true
        use-new-id-generator-mappings: true
        temp:
          use_jdbc_metadata_defaults: false

  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 831001732147-ggsjpv73kps8bchv2s8k85790qm3iv76.apps.googleusercontent.com
            client-secret: AIzaSyBvmCsalasbBKbJSqyzcTNYc4GNVzlrf6Q
            scope:
              - email
              - profile
          kakao:
            client-id: 04a820b4a5fce35c8a4255e9e7fc794f
            client-secret: oWbV6kSG5RO5inmHsf8qZf4kfrxsze2C
            redirect-uri: http://highcare.coffit.today:3000/login/oauth/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST, GET
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  profiles:
    include: oauth

# jwt secret key
jwt:
  secret: EBWJJG+CWIAKltusVjf9SL0pEfOL9xWvLnu2vClsYx7kZLH0t3R6jLCjE7OB1Jq45yIxOd3wa73/obPVhVosyQ==
  expire-time: 100000 # (밀리초 단위)
  refresh-expire-time: 1000000

  # logging config
  logging:
    level:
      root: info
image:
  add-resource-locations: file:////profileImages/
  add-resource-handler: /images/**

  image-dir: src/main/resources/static/images
  image-url: http://highcare.coffit.today:8080/images/

file:
  add-resource-locations: classpath:/static/apvFiles/
  add-resource-handler: /apvFiles/**

  upload-dir: src/main/resources/static/apvFiles
  base-url: http://highcare.coffit.today:8080/apvFiles/

